# 游戏前需等待的时间（秒）
wait_time: 60

# 被保护物品
protected:
  # 名字
  # 注：安德华拉诺特，Andvarinaut。是北欧神话中侏儒安德瓦利（Andvari）的戒指
  # 也有说法认为是手环。其名字的意思是“安德瓦利之宝”
  name: '§c§k§l|§4§l安德华拉诺特§c§k§l|'
  # 物品类型。默认为下界之星
  material: NETHER_STAR
  # 是否显示附魔闪光效果
  ench: true
  # 物品描述
  lore: []
  # 耐久设置
  durability: 3
# 商店物品设置
shop:
  material: CHEST
  name: '§6随身商店'
  lore:
    - '§a右击打开'

# 牌子设置
sign:
  # 牌子第一行的信息
  first: '§6§lApexBattle'
  # 当房间状态为等待中
  # 必须有三行，即使是空的
  waiting:
    - '§a%name%'
    - '§b在线人数§f: §e%online%'
    - '§c点击加入'
  # 当游戏正在进行时
  gaming:
    - '§a%name%'
    - '§b在线人数§f: §e%online%'
    - '§c游戏中'
  # 当游戏停止时
  stop:
    - '§a%name%'
    - '§c未开启'
    - ''

# 资源设置
resource:
  # 可无限添加
  IRON_INGOT:
    # 物品名
    name: '§f§l铁'
    # 物品类型
    material: IRON_INGOT
    # 是否显示附魔闪光效果
    ench: false
    # 物品描述
    lore: []
    # 生成间隔（秒）
    interval: 60
  GOLD_INGOT:
    # 物品名
    name: '§e§l金'
    # 物品类型
    material: GOLD_INGOT
    # 是否显示附魔闪光效果
    ench: false
    # 物品描述
    lore: []
    # 生成间隔（秒）
    interval: 120
  DIAMOND:
    # 物品名
    name: '§b§l钻石'
    # 物品类型
    material: DIAMOND
    # 是否显示附魔闪光效果
    ench: false
    # 物品描述
    lore: []
    # 生成间隔（秒）
    interval: 180

# 特殊物品设置
special:
  # 末影珍珠（载具）设置
  ENDER_PEARL:
    enabled: true
    # 加速，相对原版的末影珍珠
    # 设置为大于0并小于1的数可减速
    # 请不要设置为小于0的数或设置得过大
    vec_multiplier: 1.3

# 计分板
scoreboard:
  # 标题
  title: '§6§lApexBattle'
  # %team_count%变量替换后的格式
  team_count_format: '%name%: %count%'
  # 队伍已经输时数量的字符
  lose_symbol: '§c§l✗'
  # 计分板信息
  lines:
    - '§e地图: %map%'
    - ''
    - '§e队伍信息:'
    - '%team_count%'
    - ''
    - '§e时间: %time%秒'