# 游戏前需等待的时间（秒）
wait_time: 60

# 被保护物品
protected:
  # 名字
  # 注：安德华拉诺特，Andvarinaut。是北欧神话中侏儒安德瓦利（Andvari）的戒指
  # 也有说法认为是手环。其名字的意思是“安德瓦利之宝”
  name: '§c§k§l|§4§l安德华拉诺特§c§k§l|'
  # 物品类型。默认为下界之星
  material: NETHER_STAR
  # 是否显示附魔闪光效果
  ench: true
  # 物品描述
  lore: []
  # 耐久设置
  durability: 5
  # 拿着该物品的玩家死一次扣多少耐久？
  durability_decrease: 1

# 牌子设置
sign:
  # 当房间状态为等待中
  waiting:
    - '[ApexBattle]'
    - '%name%'
    - '在线人数: %online%'
    - '点击加入'
  # 当游戏正在进行时
  gaming:
    - '[ApexBattle]'
    - '%name%'
    - '在线人数: %online%'
    - '游戏中'
  # 当游戏停止时
  stop:
    - '[ApexBattle]'
    - '%name%'
    - '未开启'

# 资源设置
resource:
  # 可无限添加
  DIAMOND:
    # 物品名
    name: '§b§l钻石'
    # 物品类型
    material: DIAMOND
    # 是否显示附魔闪光效果
    ench: false
    # 物品描述
    lore: []
    # 生成间隔（秒）
    interval: 2
  EMERALD:
    name: '§a§l绿宝石'
    material: EMERALD
    ench: true
    lore: []
    interval: 10

# 特殊物品设置
special:
  # 末影珍珠（载具）设置
  ENDER_PEARL:
    enabled: true
    # 加速，相对原版的末影珍珠
    # 设置为大于0并小于1的数可减速
    # 请不要设置为小于0的数或设置得过大
    vec_multiplier: 1.3
  # 鞘翅（载具）设置
  ELYTRA:
    enabled: true
    # 起飞时的弹射高度
    y_addition: 5