name: ApexBattle
main: xyz.hstudio.apexbattle.ApexBattle
version: '1.1'
author: MrCraftGoo
commands:
  apex:
    description: Main command
permissions:
  apex.command.use:
    default: true
  apex.command.create:
    default: op
  apex.command.setregion:
    default: op
  apex.command.setlobby:
    default: op
  apex.command.setspectate:
    default: op
  apex.command.addresource:
    default: op
  apex.command.addteam:
    default: op
  apex.command.save:
    default: op
  apex.createsign:
    default: op